telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    name: ${TELEGRAM_BOT_NAME}
    proxy:
      enabled: ${USE_PROXY:true}
      host: ${PROXY_HOST:127.0.0.1}
      port: ${PROXY_PORT:3128}
      type: ${PROXY_TYPE:HTTP}

kinopoisk:
  url: https://api.kinopoisk.dev
  token: ${KINOPOISK_TOKEN}

backup:
  path: /usr/local/var/db/db.json

